### ISSUE TITLE
Ordinary users cannot identify

### ISSUE THREAD

**Issue by lannio** [cga-harvard/geonode#331]
After this update, this is a problem that only occurs in my instance, not in your instance.
When an ordinary user creates a map with his own uploaded layer, the identify function cannot be used in the create map page (no error in console), but it can be used normally in the map detail page. 
It is normal for administrator user to use identify function both in the create map page and map detail page.
Do you know what caused this problem?
![75](https://user-images.githubusercontent.com/33817803/38464897-b5e90b16-3b47-11e8-8713-c1fc054783fd.jpg)
![76](https://user-images.githubusercontent.com/33817803/38464898-b63464a8-3b47-11e8-8601-4265e2cb127a.jpg)

**Comment by capooti** [comment]
Can you share your django settings and local_settings file?
Maybe by email it is more appropriate better.

**Comment by capooti** [comment]
Oh yes, we are experiencing this as well. This is happening when anonymous users browse the map. Will look into it and come out with a solution.

**Comment by capooti** [comment]
This is now fixed. Let me know if you experience any regression at some point.

**Comment by blewis** [comment]
Identify does not work on multiple layers.  It should work on all layers that are turned on in the map.
Here is a map where it doesn't work. http://128.31.22.73/maps/bentest3/CE/

**Comment by lannio** [comment]
Thanks for the reply.
I will update and test later, and the results will respond to you.

**Comment by lannio** [comment]
Hi @capooti ,
This problem still exists and I found the reason.
I think it is a permission problem.
I used the lanni account to upload two layers, one is “ch_highered_public_2_eze_1”, permission is “anyone cannot download”, the other is “high_speed_rail_lines_2016_40k_1” permission is “anyone can download”.
![11](https://user-images.githubusercontent.com/33817803/38798622-a4e95d40-4194-11e8-8033-d1b53822b3b4.png)
![12](https://user-images.githubusercontent.com/33817803/38798623-a51d5e2e-4194-11e8-836d-19b11efa25c2.png)
Then I created a map with these two layers (http://128.31.22.73/maps/80).
In the details page, both layers can be identified.
![image](https://user-images.githubusercontent.com/33817803/38798792-2a02ed70-4195-11e8-96d8-d0597d748b57.png)
But in the view page, only “high_speed_rail_lines_2016_40k_1”can be identified, but “ch_highered_public_2_eze_1” cannot.
![image](https://user-images.githubusercontent.com/33817803/38798832-509a8ab0-4195-11e8-9005-bfa83190f4a9.png)
Even if the two layers are uploaded by lanni, the map is created by lanni. When the permission of “ch_highered_public_2_eze_1” is “anyone cannot download”, lanni cannot identify it. Only the administrator users can identify it.
![image](https://user-images.githubusercontent.com/33817803/38799220-6f93ac2a-4196-11e8-9e3d-0009325335f1.png)
I think the state of the detail page is normal. Even if the permission of a layer is “anyone cannot download”, it should can be identified.

**Comment by capooti** [comment]
It is not connected to permissions. It is correctly working for me in Firefox:

![screenshot 2018-04-16 15 27 18](https://user-images.githubusercontent.com/148380/38830588-d0b7d94c-418a-11e8-81f0-271e48ea9d42.png)

Which browser are you using? Can you try to force reload the cache, particularly all of the javascript files?

**Comment by capooti** [comment]
Dear @lannio, thanks a lot for debugging. You are definitely correct: download permission is needed, as Identify is using WFS endpoint in order to work (GetFeatureInfo operation), which requires the feature to be identified to be downloadable.
This is handled differently in the standard GeoNode viewer: the request is being sent to the WMS endpoint (GetFeatureInfo operation), so the "Who can download it" permission is not being checked.
Let me discuss about this with @bglewis and we will be back to you.

**Comment by lannio** [comment]
Thank you, I will feedback after testing.
